# SPDX-License-Identifier: MIT
# Copyright (C) 2026 VIKINGYFY

name: IPQ60XX

on:
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: false
        required: false
        type: boolean

permissions: write-all

jobs:
  config:
    name: ${{ matrix.CONFIG }}
    strategy:
      fail-fast: false
      matrix:
        CONFIG: [IPQ60XX-WIFI-YES]
        SOURCE: [VIKINGYFY/immortalwrt]
        BRANCH: [main]
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_CONFIG: ${{ matrix.CONFIG }}
      WRT_THEME: aurora
      WRT_NAME: OWRT
      WRT_SSID: OWRT
      WRT_WORD: 12345678
      WRT_IP: 192.168.10.1
      WRT_PW: 无
      WRT_REPO: https://github.com/${{ matrix.SOURCE }}.git
      WRT_BRANCH: ${{ matrix.BRANCH }}
      WRT_SOURCE: ${{ matrix.SOURCE }}
      WRT_PACKAGE: ${{ inputs.PACKAGE }}
      WRT_TEST: ${{ inputs.TEST || false }}
